language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
dist: trusty
env:
  global:
  - EXTRA_DEPS="inotify"
  - PINS="datakit-client:. datakit-server:. datakit-github:. datakit:."
  matrix:
  - OCAML_VERSION=4.02 PACKAGE="datakit-client"
  - OCAML_VERSION=4.03 PACKAGE="datakit-client"
  - OCAML_VERSION=4.03 PACKAGE="datakit-server"
  - OCAML_VERSION=4.03 PACKAGE="datakit-github"
  - OCAML_VERSION=4.03 PACKAGE="datakit-ci"
  - OCAML_VERSION=4.03 PACKAGE="datakit"
os:
  - linux
